### ISSUE TITLE
Error when trying to open any Org file

### ISSUE THREAD

**Issue by hrqmonteiro** [kristijanhusak/orgmode.nvim#6]
![error](https://user-images.githubusercontent.com/17055027/123642180-61a58c80-d7f9-11eb-89eb-d43d09837e41.png)

**Comment by kristijanhusak** [comment]
Can you tell me which colorscheme are you using?

**Comment by hrqmonteiro** [comment]
> Can you tell me which colorscheme are you using?

[NeoSolarized](https://github.com/overcache/NeoSolarized), but tried using Nord as well, same error.

**Comment by hrqmonteiro** [comment]
> > Can you tell me which colorscheme are you using?
> 
> [NeoSolarized](https://github.com/overcache/NeoSolarized), but tried using Nord as well, same error.

Edit: tried using Tokyonight now, same error. Don't think the colorscheme is the problem.

**Comment by kristijanhusak** [comment]
I just tried this minimal init and worked fine:

```lua
vim.cmd("packadd! orgmode.nvim")
vim.cmd("packadd! tokyonight.nvim")

vim.o.background = 'dark'
vim.cmd('colorscheme tokyonight')

require("orgmode").setup({
	org_agenda_files = { "~/Dropbox/orgmode/*", "~/local-org/**/*" },
	org_default_notes_file = "~/Dropbox/org/refile.org",
})
```

```
nvim -u minimal.lua --noplugin
```

![screenshot](https://i.imgur.com/986mze2.png)

Can you try the same?

**Comment by garcia5** [comment]
I get the same error even with the `minimal.lua` config -- using [moonlight.nvim](https://github.com/shaunsingh/moonlight.nvim) colorscheme

```lua
-- minimal.lua
vim.cmd("packadd! orgmode.nvim")
vim.cmd("packadd! moonlight.nvim")

vim.o.background = 'dark'
vim.cmd('colorscheme moonlight')

require("orgmode").setup({
        org_agenda_files = { "~/Dropbox/orgmode/*", "~/local-org/**/*" },
        org_default_notes_file = "~/Dropbox/org/refile.org",
})
```

![image](https://user-images.githubusercontent.com/21695295/123656577-0c1fae80-d7fe-11eb-9951-873e569a3783.png)

`E5108: Error executing lua ...pack/paqs/start/orgmode.nvim/lua/orgmode/agenda/init.lua:183: Vim(lua):E5108: Error executing lua ...ck/paqs/start/orgmode.nvim/lua/orgmode/colors/colors.lua:143: attempt to perform arithmetic on field 'L' (a nil value)`

**Comment by kristijanhusak** [comment]
@garcia5 Thanks.

I just pushed a fix that should fix these issues. It would be great if all who had issues give it another test after the update to see if it works now.

**Comment by garcia5** [comment]
Working now! Thanks for the quick turnaround

**Comment by nickmagginas** [comment]
Hi oh!
Had the same problem with [rose-pine](https://github.com/rose-pine/neovim). It is fixed now. Thanks for the awesome plugin

**Comment by aareman** [comment]
Hi, 
@kristijanhusak  thanks for your hard work. Would love to get more into ORG mode, seems pretty cool!

Still getting the same issue 
![image](https://user-images.githubusercontent.com/10500823/123802006-ce339080-d8b8-11eb-87c2-2cd704c46e2a.png)

Just updated to newest changes. I'm not using termguicolors if that is the issue. Using the pywal.vim color theme.

**Comment by kristijanhusak** [comment]
@aareman Thanks, it's probably issue with missing gui colors in pywal.vim. I'll take a look.

**Comment by aareman** [comment]
Yeah, there are no GUI colors. And if there were it wouldn't use them anyway since termguicolors is not set

Avraham Areman,

Director of Engineering

Dynamic Healthcare Solutions.


Sent from my phone, please excuse any typos.


________________________________

**Comment by kristijanhusak** [comment]
@aareman I just pushed a fix. Should be working now, and it should have some basic coloring for cterm. Let me know if it works.

**Comment by aareman** [comment]
I updated and now I can open the agenda `<leader>oa`, but now `<leader>oc` is not working. (note error occurs after pressint "t" for task)

![image](https://user-images.githubusercontent.com/10500823/123966531-83327f80-d983-11eb-99be-eaca883a3115.png)

**Comment by kristijanhusak** [comment]
@aareman Are you sure you have the latest master? The function that it tries to call was removed this morning, there are no any references to it anywhere else.

**Comment by aareman** [comment]
@kristijanhusak I see there are new commits since I updated early this morning 3 commits ~ 2hours ago. Just updated. now its working. Thank you, I'll let you know if anything else comes up. Thank you for giving me a reason to learn org ;)

**Comment by aareman** [comment]
@***@***.***> that was what I was suggesting, but I wasn't sure how to actually do it, so thank you for the awesome snippet ;)

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
